import {
  CASHIER_ID,
  CASHIER_NAME,
  CASHIER_STATE_VERSION,
  CASHIER_TERMINAL,
  DEFAULT_DELAY_THRESHOLD_MINUTES,
} from "../constants";
import type {
  CashierState,
  Order,
  OrderItem,
  OrderStatus,
  PaymentMethod,
} from "../types";

const ago = (minutes: number) =>
  new Date(Date.now() - minutes * 60_000).toISOString();
const item = (
  id: string,
  menuItemId: string,
  name: string,
  unitPrice: number,
  quantity: number,
): OrderItem => ({
  id,
  menuItemId,
  name,
  unitPrice,
  quantity,
});

const makeOrder = (input: {
  id: string;
  customerName: string;
  contactNumber: string;
  deliveryAddress?: string;
  type: Order["type"];
  tableNumber?: string;
  items: OrderItem[];
  status: OrderStatus;
  paymentMethod: PaymentMethod;
  paymentStatus: Order["paymentStatus"];
  minutesAgo: number;
  paymentId?: string;
  transactionId?: string;
  assignedRider?: string;
  riderStatus?: string;
  discountAmount?: number;
}): Order => {
  const subtotal = input.items.reduce(
    (sum, entry) => sum + entry.unitPrice * entry.quantity,
    0,
  );
  const timestamp = ago(input.minutesAgo);
  return {
    id: input.id,
    customerName: input.customerName,
    contactNumber: input.contactNumber,
    deliveryAddress: input.deliveryAddress,
    type: input.type,
    tableNumber: input.tableNumber,
    items: input.items,
    subtotal,
    discountType: null,
    discountAmount: input.discountAmount ?? 0,
    total: subtotal - (input.discountAmount ?? 0),
    paymentId: input.paymentId,
    transactionId: input.transactionId,
    paymentMethod: input.paymentMethod,
    paymentStatus: input.paymentStatus,
    status: input.status,
    assignedRider: input.assignedRider,
    riderStatus: input.riderStatus,
    createdAt: timestamp,
    updatedAt: timestamp,
    cashierId: input.type === "Delivery" ? undefined : CASHIER_ID,
    shiftId: input.paymentStatus === "Verified" ? "SHIFT-CURRENT-01" : undefined,
    timeline: [
      {
        id: `EVT-${input.id}-1`,
        status: input.type === "Delivery" ? "Awaiting Payment" : "Confirmed",
        label:
          input.type === "Delivery"
            ? "Order submitted"
            : "Walk-in order created",
        timestamp,
        actor: input.type === "Delivery" ? "Customer" : CASHIER_NAME,
      },
      ...(input.status !== "Awaiting Payment" && input.status !== "Confirmed"
        ? [
            {
              id: `EVT-${input.id}-2`,
              status: input.status,
              label: `Order marked ${input.status.toLowerCase()}`,
              timestamp: ago(Math.max(1, input.minutesAgo - 5)),
              actor:
                input.status.includes("Delivery") ||
                input.status === "Picked Up"
                  ? (input.assignedRider ?? "Rider")
                  : "Kitchen Staff",
            },
          ]
        : []),
    ],
  };
};

export function createInitialCashierState(): CashierState {
  const orders: Order[] = [
    makeOrder({
      id: "ORD-2048",
      customerName: "Walk-in Customer",
      contactNumber: "—",
      type: "Dine-in",
      tableNumber: "4",
      items: [
        item("OI-81", "MENU-01", "Crispy Beef Tadyang", 185, 2),
        item("OI-82", "MENU-08", "White Rice", 35, 2),
        item("OI-83", "MENU-09", "Softdrinks", 30, 2),
      ],
      status: "Completed",
      paymentMethod: "Cash",
      paymentStatus: "Verified",
      minutesAgo: 105,
      paymentId: "PAY-9108",
      transactionId: "TXN-4108",
    }),
    makeOrder({
      id: "ORD-2047",
      customerName: "Ana Reyes",
      contactNumber: "09394567890",
      deliveryAddress: "56 Ortigas Ave., Mandaluyong",
      type: "Delivery",
      items: [
        item("OI-71", "MENU-03", "Sinigang na Baka", 155, 1),
        item("OI-72", "MENU-08", "White Rice", 35, 2),
      ],
      status: "Out for Delivery",
      paymentMethod: "GCash",
      paymentStatus: "Verified",
      minutesAgo: 68,
      paymentId: "PAY-9107",
      transactionId: "TXN-4107",
      assignedRider: "Danilo Cruz",
      riderStatus: "Out for Delivery",
    }),
    makeOrder({
      id: "ORD-2046",
      customerName: "Walk-in Customer",
      contactNumber: "—",
      type: "Take-out",
      items: [
        item("OI-61", "MENU-05", "Kare-Kare", 175, 1),
        item("OI-62", "MENU-08", "White Rice", 35, 1),
      ],
      status: "Ready",
      paymentMethod: "Cash",
      paymentStatus: "Verified",
      minutesAgo: 32,
      paymentId: "PAY-9106",
      transactionId: "TXN-4106",
    }),
    makeOrder({
      id: "ORD-2045",
      customerName: "Maria Santos",
      contactNumber: "09172345678",
      deliveryAddress: "89 Del Pilar St., Pasig",
      type: "Delivery",
      items: [
        item("OI-51", "MENU-01", "Crispy Beef Tadyang", 185, 1),
        item("OI-52", "MENU-08", "White Rice", 35, 1),
        item("OI-53", "MENU-10", "Buko Juice", 35, 1),
      ],
      status: "Preparing",
      paymentMethod: "GCash",
      paymentStatus: "Verified",
      minutesAgo: 24,
      paymentId: "PAY-9105",
      transactionId: "TXN-4105",
    }),
    makeOrder({
      id: "ORD-2044",
      customerName: "Roberto Lim",
      contactNumber: "09171234567",
      deliveryAddress: "45 Rizal St., Taguig",
      type: "Delivery",
      items: [
        item("OI-41", "MENU-01", "Crispy Beef Tadyang", 185, 2),
        item("OI-42", "MENU-08", "White Rice", 35, 2),
      ],
      status: "Awaiting Payment",
      paymentMethod: "GCash",
      paymentStatus: "Pending",
      minutesAgo: 18,
      paymentId: "PAY-9104",
    }),
    makeOrder({
      id: "ORD-2043",
      customerName: "Grace Villanueva",
      contactNumber: "09282345678",
      deliveryAddress: "12 Mabini Ave., Makati",
      type: "Delivery",
      items: [
        item("OI-31", "MENU-03", "Sinigang na Baka", 155, 1),
        item("OI-32", "MENU-08", "White Rice", 35, 1),
      ],
      status: "Awaiting Payment",
      paymentMethod: "GCash",
      paymentStatus: "Pending",
      minutesAgo: 11,
      paymentId: "PAY-9103",
    }),
    makeOrder({
      id: "ORD-2042",
      customerName: "Mark Castillo",
      contactNumber: "09393456789",
      deliveryAddress: "78 Quezon Blvd., Quezon City",
      type: "Delivery",
      items: [
        item("OI-21", "MENU-05", "Kare-Kare", 175, 1),
        item("OI-22", "MENU-08", "White Rice", 35, 2),
        item("OI-23", "MENU-10", "Buko Juice", 35, 1),
      ],
      status: "Awaiting Payment",
      paymentMethod: "GCash",
      paymentStatus: "Pending",
      minutesAgo: 6,
      paymentId: "PAY-9102",
    }),
    makeOrder({
      id: "ORD-2041",
      customerName: "Carlos Mendoza",
      contactNumber: "09275678901",
      deliveryAddress: "23 Katipunan Ave., Quezon City",
      type: "Delivery",
      items: [
        item("OI-11", "MENU-02", "Adobong Manok", 120, 2),
        item("OI-12", "MENU-07", "Fried Rice", 45, 2),
      ],
      status: "Rider Accepted",
      paymentMethod: "GCash",
      paymentStatus: "Verified",
      minutesAgo: 46,
      paymentId: "PAY-9101",
      transactionId: "TXN-4101",
      assignedRider: "Ramil Abad",
      riderStatus: "Rider Accepted",
    }),
  ];

  return {
    version: CASHIER_STATE_VERSION,
    cashier: { id: CASHIER_ID, name: CASHIER_NAME, terminal: CASHIER_TERMINAL },
    delayedThresholdMinutes: DEFAULT_DELAY_THRESHOLD_MINUTES,
    menuItems: [
      {
        id: "MENU-01",
        name: "Crispy Beef Tadyang",
        category: "Viands",
        description: "Crispy beef ribs with garlic and spices",
        price: 185,
        available: true,
        preparationMinutes: 18,
      },
      {
        id: "MENU-02",
        name: "Adobong Manok",
        category: "Viands",
        description: "Classic chicken adobo",
        price: 120,
        available: true,
        preparationMinutes: 14,
      },
      {
        id: "MENU-03",
        name: "Sinigang na Baka",
        category: "Soups",
        description: "Tamarind beef soup with vegetables",
        price: 155,
        available: true,
        preparationMinutes: 16,
      },
      {
        id: "MENU-04",
        name: "Chicken Bicol Express",
        category: "Viands",
        description: "Spicy chicken in coconut milk",
        price: 130,
        available: false,
        preparationMinutes: 15,
      },
      {
        id: "MENU-05",
        name: "Kare-Kare",
        category: "Viands",
        description: "Peanut stew with vegetables",
        price: 175,
        available: true,
        preparationMinutes: 20,
      },
      {
        id: "MENU-06",
        name: "Pinakbet",
        category: "Vegetables",
        description: "Mixed vegetables in shrimp paste",
        price: 110,
        available: true,
        preparationMinutes: 12,
      },
      {
        id: "MENU-07",
        name: "Fried Rice",
        category: "Rice",
        description: "Garlic fried rice",
        price: 45,
        available: true,
        preparationMinutes: 8,
      },
      {
        id: "MENU-08",
        name: "White Rice",
        category: "Rice",
        description: "Steamed white rice",
        price: 35,
        available: true,
        preparationMinutes: 4,
      },
      {
        id: "MENU-09",
        name: "Softdrinks",
        category: "Beverages",
        description: "Coke, Royal, or Sprite",
        price: 30,
        available: true,
      },
      {
        id: "MENU-10",
        name: "Buko Juice",
        category: "Beverages",
        description: "Fresh coconut juice",
        price: 35,
        available: true,
      },
    ],
    orders,
    payments: [
      {
        id: "PAY-9108",
        orderId: "ORD-2048",
        method: "Cash",
        amount: 500,
        submittedAmount: 500,
        status: "Verified",
        uploadedAt: ago(105),
        verifiedBy: CASHIER_ID,
        verifiedAt: ago(105),
      },
      {
        id: "PAY-9107",
        orderId: "ORD-2047",
        method: "GCash",
        amount: 225,
        submittedAmount: 225,
        status: "Verified",
        referenceNumber: "GC-882014",
        uploadedAt: ago(70),
        verifiedBy: CASHIER_ID,
        verifiedAt: ago(68),
      },
      {
        id: "PAY-9106",
        orderId: "ORD-2046",
        method: "Cash",
        amount: 210,
        submittedAmount: 210,
        status: "Verified",
        uploadedAt: ago(32),
        verifiedBy: CASHIER_ID,
        verifiedAt: ago(32),
      },
      {
        id: "PAY-9105",
        orderId: "ORD-2045",
        method: "GCash",
        amount: 255,
        submittedAmount: 255,
        status: "Verified",
        referenceNumber: "GC-882019",
        uploadedAt: ago(26),
        verifiedBy: CASHIER_ID,
        verifiedAt: ago(24),
      },
      {
        id: "PAY-9104",
        orderId: "ORD-2044",
        method: "GCash",
        amount: 440,
        submittedAmount: 440,
        status: "Pending",
        referenceNumber: "GC-882024",
        proofLabel: "GCash payment to RRJ Food-House",
        uploadedAt: ago(16),
      },
      {
        id: "PAY-9103",
        orderId: "ORD-2043",
        method: "GCash",
        amount: 190,
        submittedAmount: 180,
        status: "Pending",
        referenceNumber: "GC-882026",
        proofLabel: "GCash payment to RRJ Food-House",
        uploadedAt: ago(9),
      },
      {
        id: "PAY-9102",
        orderId: "ORD-2042",
        method: "GCash",
        amount: 280,
        submittedAmount: 280,
        status: "Pending",
        referenceNumber: "GC-882029",
        proofLabel: "GCash payment to RRJ Food-House",
        uploadedAt: ago(5),
      },
      {
        id: "PAY-9101",
        orderId: "ORD-2041",
        method: "GCash",
        amount: 330,
        submittedAmount: 330,
        status: "Verified",
        referenceNumber: "GC-882010",
        uploadedAt: ago(48),
        verifiedBy: CASHIER_ID,
        verifiedAt: ago(46),
      },
    ],
    transactions: [
      {
        id: "TXN-4108",
        orderId: "ORD-2048",
        customerName: "Walk-in Customer",
        amount: 500,
        discountAmount: 0,
        method: "Cash",
        status: "Completed",
        cashierId: CASHIER_ID,
        cashierName: CASHIER_NAME,
        shiftId: "SHIFT-CURRENT-01",
        paymentId: "PAY-9108",
        createdAt: ago(105),
      },
      {
        id: "TXN-4107",
        orderId: "ORD-2047",
        customerName: "Ana Reyes",
        amount: 225,
        discountAmount: 0,
        method: "GCash",
        status: "Completed",
        cashierId: CASHIER_ID,
        cashierName: CASHIER_NAME,
        shiftId: "SHIFT-CURRENT-01",
        paymentId: "PAY-9107",
        createdAt: ago(68),
      },
      {
        id: "TXN-4106",
        orderId: "ORD-2046",
        customerName: "Walk-in Customer",
        amount: 210,
        discountAmount: 0,
        method: "Cash",
        status: "Completed",
        cashierId: CASHIER_ID,
        cashierName: CASHIER_NAME,
        shiftId: "SHIFT-CURRENT-01",
        paymentId: "PAY-9106",
        createdAt: ago(32),
      },
      {
        id: "TXN-4105",
        orderId: "ORD-2045",
        customerName: "Maria Santos",
        amount: 255,
        discountAmount: 0,
        method: "GCash",
        status: "Completed",
        cashierId: CASHIER_ID,
        cashierName: CASHIER_NAME,
        shiftId: "SHIFT-CURRENT-01",
        paymentId: "PAY-9105",
        createdAt: ago(24),
      },
      {
        id: "TXN-4101",
        orderId: "ORD-2041",
        customerName: "Carlos Mendoza",
        amount: 330,
        discountAmount: 0,
        method: "GCash",
        status: "Completed",
        cashierId: CASHIER_ID,
        cashierName: CASHIER_NAME,
        shiftId: "SHIFT-CURRENT-01",
        paymentId: "PAY-9101",
        createdAt: ago(46),
      },
    ],
    shifts: [
      {
        id: "SHIFT-CURRENT-01",
        cashierId: CASHIER_ID,
        cashierName: CASHIER_NAME,
        terminal: CASHIER_TERMINAL,
        openingCash: 4000,
        startedAt: ago(150),
        status: "Open",
      },
    ],
    riders: [
      {
        id: "RIDER-01",
        name: "Danilo Cruz",
        availability: "Assigned",
        currentOrderId: "ORD-2047",
      },
      {
        id: "RIDER-02",
        name: "Ramil Abad",
        availability: "Assigned",
        currentOrderId: "ORD-2041",
      },
      {
        id: "RIDER-03",
        name: "Joel Ramos",
        availability: "Available",
      },
    ],
    notifications: [
      {
        id: "NOTE-01",
        title: "Order ready",
        message: "ORD-2046 is ready for release.",
        createdAt: ago(3),
        read: false,
        kind: "kitchen_ready",
        page: "order-list",
        intent: { statuses: ["Ready"], search: "ORD-2046" },
        orderId: "ORD-2046",
      },
      {
        id: "NOTE-02",
        title: "New payment proof",
        message: "ORD-2042 submitted a GCash proof.",
        createdAt: ago(5),
        read: false,
        kind: "payment_submitted",
        page: "pending-payments",
        orderId: "ORD-2042",
      },
      {
        id: "NOTE-03",
        title: "Delayed order",
        message: "ORD-2041 has exceeded the 20-minute attention threshold.",
        createdAt: ago(8),
        read: true,
        kind: "order_delayed",
        page: "order-list",
        intent: { search: "ORD-2041" },
        orderId: "ORD-2041",
      },
      {
        id: "NOTE-04",
        title: "Rider accepted delivery",
        message: "Ramil Abad accepted ORD-2041.",
        createdAt: ago(12),
        read: true,
        kind: "rider_accepted",
        page: "order-list",
        intent: { search: "ORD-2041" },
        orderId: "ORD-2041",
      },
    ],
    activities: [
      {
        id: "ACT-05",
        kind: "kitchen_ready",
        message: "Kitchen marked ORD-2046 ready",
        orderId: "ORD-2046",
        actor: "Kitchen Staff",
        timestamp: ago(3),
      },
      {
        id: "ACT-04",
        kind: "rider_accepted",
        message: "Ramil Abad accepted ORD-2041",
        orderId: "ORD-2041",
        actor: "Ramil Abad",
        timestamp: ago(12),
      },
      {
        id: "ACT-03",
        kind: "payment_verified",
        message: "Payment verified for ORD-2045",
        orderId: "ORD-2045",
        transactionId: "TXN-4105",
        actor: CASHIER_NAME,
        timestamp: ago(24),
      },
      {
        id: "ACT-02",
        kind: "transaction_completed",
        message: "Cash transaction completed for ORD-2046",
        orderId: "ORD-2046",
        transactionId: "TXN-4106",
        actor: CASHIER_NAME,
        timestamp: ago(32),
      },
      {
        id: "ACT-01",
        kind: "payment_verified",
        message: "Payment verified for ORD-2041",
        orderId: "ORD-2041",
        transactionId: "TXN-4101",
        actor: CASHIER_NAME,
        timestamp: ago(46),
      },
    ],
    heldOrders: [],
  };
}
